require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProductSectionsController, type: :controller do

  let(:product_section) {
    FactoryGirl.create(:valid_product_section)
  }
  # This should return the minimal set of attributes required to create a valid
  # ProductSection. As you add validations to ProductSection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:valid_product_section)
  }

  let(:invalid_attributes) {
    FactoryGirl.attributes_for(:invalid_product_section)
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductSectionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all product_sections as @product_sections" do
      
      get :index, {}, valid_session
      expect(assigns(:product_sections)).to eq([product_section])
    end
  end

  describe "GET #show" do
    it "assigns the requested product_section as @product_section" do
      
      get :show, {:id => product_section.to_param}, valid_session
      expect(assigns(:product_section)).to eq(product_section)
    end
  end

  describe "GET #new" do
    it "assigns a new product_section as @product_section" do
      get :new, {}, valid_session
      expect(assigns(:product_section)).to be_a_new(ProductSection)
    end
  end

  describe "GET #edit" do
    it "assigns the requested product_section as @product_section" do
      
      get :edit, {:id => product_section.to_param}, valid_session
      expect(assigns(:product_section)).to eq(product_section)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ProductSection" do
        expect {
          post :create, {:product_section => valid_attributes}, valid_session
        }.to change(ProductSection, :count).by(1)
      end

      it "assigns a newly created product_section as @product_section" do
        post :create, {:product_section => valid_attributes}, valid_session
        expect(assigns(:product_section)).to be_a(ProductSection)
        expect(assigns(:product_section)).to be_persisted
      end

      it "redirects to the created product_section" do
        post :create, {:product_section => valid_attributes}, valid_session
        expect(response).to redirect_to(ProductSection.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved product_section as @product_section" do
        post :create, {:product_section => invalid_attributes}, valid_session
        expect(assigns(:product_section)).to be_a_new(ProductSection)
      end

      it "re-renders the 'new' template" do
        post :create, {:product_section => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        FactoryGirl.attributes_for(:valid_product_section, title_en: "new english title")
      }

      it "updates the requested product_section" do
        
        put :update, {:id => product_section.to_param, :product_section => new_attributes}, valid_session
        product_section.reload
        expect(assigns(:product_section).title_en).to eq "new english title"
      end

      it "assigns the requested product_section as @product_section" do
        
        put :update, {:id => product_section.to_param, :product_section => valid_attributes}, valid_session
        expect(assigns(:product_section)).to eq(product_section)
      end

      it "redirects to the product_section" do
        
        put :update, {:id => product_section.to_param, :product_section => valid_attributes}, valid_session
        expect(response).to redirect_to(product_section)
      end
    end

    context "with invalid params" do
      it "assigns the product_section as @product_section" do
        
        put :update, {:id => product_section.to_param, :product_section => invalid_attributes}, valid_session
        expect(assigns(:product_section)).to eq(product_section)
      end

      it "re-renders the 'edit' template" do
        
        put :update, {:id => product_section.to_param, :product_section => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested product_section" do
      
      # expect {
      #   delete :destroy, {:id => product_section.to_param}, valid_session
      # }.to change(ProductSection, :count).by(-1)
    end

    it "redirects to the product_sections list" do
      
      delete :destroy, {:id => product_section.to_param}, valid_session
      expect(response).to redirect_to(product_sections_url)
    end
  end

end
